# Generated by Django 3.2.9 on 2021-11-22 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.FileField(upload_to='csv_files')),
                ('csv_filename', models.CharField(db_index=True, max_length=1024, unique=True)),
            ],
        ),
    ]
